/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Decimal = string;
export type Binary = string;
export interface InstantiateMsg {
  fee?: Coin | null;
  name_nft_addr: string;
  verification_threshold: Decimal;
  verifier_pubkeys: Binary[];
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  claim: {
    name: string;
    referral?: string | null;
    verifications: Verification[];
    verifying_msg: string;
  };
} | {
  update_verifier_pubkeys: {
    add: Binary[];
    remove: Binary[];
  };
} | {
  set_verification_threshold: {
    threshold: Decimal;
  };
} | {
  set_name_n_f_t_address: {
    name_nft_address: string;
  };
} | {
  set_fee: {
    fee?: Coin | null;
  };
} | {
  withdraw_funds: {
    amount: Coin[];
    to_address: string;
  };
};
export interface Verification {
  public_key: Binary;
  signature: Binary;
}
export type QueryMsg = {
  verifier_pub_keys: {};
} | {
  verification_threshold: {};
} | {
  name_n_f_t_address: {};
} | {
  referral_count: {
    name: string;
  };
} | {
  fee: {};
} | {
  name_by_twitter_id: {
    twitter_id: string;
  };
};
export interface MigrateMsg {}
export interface FeeResponse {
  fee?: Coin | null;
}
export interface NameByTwitterIdResponse {
  name: string;
}
export interface NameNFTAddressResponse {
  name_nft_address: string;
}
export interface ReferralCountResponse {
  count: number;
}
export interface VerificationThresholdResponse {
  verification_threshold_percentage: Decimal;
}
export interface VerifierPubKeysResponse {
  verifier_pubkeys: Binary[];
}