/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./IcnsNameNft.types";
import * as _1 from "./IcnsNameNft.client";
import * as _2 from "./IcnsRegistrar.types";
import * as _3 from "./IcnsRegistrar.client";
import * as _4 from "./IcnsResolver.types";
import * as _5 from "./IcnsResolver.client";
export namespace contracts {
  export const IcnsNameNft = { ..._0,
    ..._1
  };
  export const IcnsRegistrar = { ..._2,
    ..._3
  };
  export const IcnsResolver = { ..._4,
    ..._5
  };
}