/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./IcnsNameNft.client";
import * as _3 from "./IcnsRegistrar.client";
import * as _5 from "./IcnsResolver.client";
export declare namespace contracts {
    const IcnsNameNft: {
        IcnsNameNftQueryClient: typeof _1.IcnsNameNftQueryClient;
        IcnsNameNftClient: typeof _1.IcnsNameNftClient;
    };
    const IcnsRegistrar: {
        IcnsRegistrarQueryClient: typeof _3.IcnsRegistrarQueryClient;
        IcnsRegistrarClient: typeof _3.IcnsRegistrarClient;
    };
    const IcnsResolver: {
        IcnsResolverQueryClient: typeof _5.IcnsResolverQueryClient;
        IcnsResolverClient: typeof _5.IcnsResolverClient;
    };
}
//# sourceMappingURL=index.d.ts.map