on: push
name: CosmWasm
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Build contracts
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --lib --release --target wasm32-unknown-unknown
        env:
          RUST_BACKTRACE: 1
